{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d33ad16d-4b65-4c7d-815f-91cff115305a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import json\n",
    "import pandas as pd\n",
    "from sdig.erddap.info import Info\n",
    "import datetime\n",
    "import ssl\n",
    "import dateutil\n",
    "import constants\n",
    "ssl._create_default_https_context = ssl._create_unverified_context"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "1d476d70-afe1-481d-bf13-6810a3ca3881",
   "metadata": {},
   "outputs": [],
   "source": [
    "with open(\"config/start_config.json\", \"r+\") as site_file:\n",
    "    site_json = json.load(site_file)\n",
    "all_start_seconds = 999999999999999999999\n",
    "all_end_seconds = -1\n",
    "for site in site_json:\n",
    "\n",
    "    url = site_json[site]['url']\n",
    "\n",
    "    info = Info(url)\n",
    "    \n",
    "    variables, long_names, units, stardard_names, var_types = info.get_variables()\n",
    "    not_null = ''\n",
    "    for var in site_json[site]['variables']:\n",
    "        not_null = not_null + '&' + var + '!=NaN'\n",
    "    time_url = url + '.csv?time&orderByMinMax(\"time\")'+not_null\n",
    "    print(time_url)\n",
    "    df = pd.read_csv(time_url, skiprows=[1])\n",
    "    start_date = df['time'].min()\n",
    "    end_date = df['time'].max()\n",
    "    starto = dateutil.parser.isoparse(start_date)\n",
    "    endo = dateutil.parser.isoparse(end_date)\n",
    "    start_date = datetime.datetime.strftime(starto, constants.d_format)\n",
    "    end_date = datetime.datetime.strftime(endo, constants.d_format)\n",
    "    start_date_seconds = starto.timestamp()\n",
    "    end_date_seconds = endo.timestamp()\n",
    "    time_marks = Info.get_time_marks(start_date_seconds, end_date_seconds)\n",
    "    site_json[site]['start_date'] = start_date\n",
    "    site_json[site]['start_date_seconds'] = start_date_seconds\n",
    "    if start_date_seconds < all_start_seconds:\n",
    "        all_start_seconds = start_date_seconds\n",
    "        all_start = start_date\n",
    "    if end_date_seconds > all_end_seconds:\n",
    "        all_end_seconds = end_date_seconds\n",
    "        all_end = end_date\n",
    "    site_json[site]['end_date'] = end_date\n",
    "    site_json[site]['end_date_seconds'] = end_date_seconds\n",
    "    site_json[site]['long_names'] = long_names\n",
    "    site_json[site]['units'] = units\n",
    "    site_json[site]['time_marks'] = time_marks\n",
    "    site_json[site]['title'] = info.get_title()\n",
    "    if site_json[site]['depth_name'] == \"None\":\n",
    "        site_json[site]['has_depth'] = \"false\"\n",
    "    else:\n",
    "        site_json[site]['has_depth'] = \"true\"\n",
    "    if site_json[site]['pressure_name'] == \"None\":\n",
    "        site_json[site]['has_pressure'] = \"false\"\n",
    "    else:\n",
    "        site_json[site]['has_pressure'] = \"true\"\n",
    "config = {}\n",
    "config['all_start'] = all_start\n",
    "config['all_end'] = all_end\n",
    "config['all_start_seconds'] = all_start_seconds\n",
    "config['all_end_seconds'] = all_end_seconds\n",
    "config['sites'] = site_json\n",
    "print('There are ', len(site_json), ' sites configured.')\n",
    "print(all_start, all_end)\n",
    "with open('config/sites.json', 'w') as fp:\n",
    "    json.dump(config, fp, indent=4)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d4ebfbfd-5b07-4a85-b66f-63bd770512ce",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unexpected exception formatting exception. Falling back to standard exception\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Traceback (most recent call last):\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 3508, in run_code\n",
      "  File \"/tmp/ipykernel_4099/1598290540.py\", line 2, in <module>\n",
      "    tasks.load_locations()\n",
      "  File \"/home/workspaceuser/app/tasks.py\", line 36, in load_locations\n",
      "    locations_df.to_sql(constants.location_table, constants.postgres_engine, if_exists='replace', index=False, chunksize=1500, method='multi')\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/pandas/core/generic.py\", line 2605, in to_sql\n",
      "    sql.to_sql(\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/pandas/io/sql.py\", line 589, in to_sql\n",
      "    pandas_sql.to_sql(\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/pandas/io/sql.py\", line 1393, in to_sql\n",
      "    table.create()\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/pandas/io/sql.py\", line 721, in create\n",
      "    if self.exists():\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/pandas/io/sql.py\", line 708, in exists\n",
      "    return self.pd_sql.has_table(self.name, self.schema)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/pandas/io/sql.py\", line 1430, in has_table\n",
      "    return self.connectable.run_callable(\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 2211, in run_callable\n",
      "    with self._contextual_connect() as conn:\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 2302, in _contextual_connect\n",
      "    self._wrap_pool_connect(self.pool.connect, None),\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 2336, in _wrap_pool_connect\n",
      "    return fn()\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 364, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 778, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 495, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/pool/impl.py\", line 241, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 309, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 440, in __init__\n",
      "    self.__connect(first_connect_check=True)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/pool/base.py\", line 664, in __connect\n",
      "    pool.dispatch.first_connect.for_modify(\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/event/attr.py\", line 314, in exec_once_unless_exception\n",
      "    self._exec_once_impl(True, *args, **kw)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/event/attr.py\", line 285, in _exec_once_impl\n",
      "    self(*args, **kw)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/event/attr.py\", line 322, in __call__\n",
      "    fn(*args, **kw)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py\", line 1397, in go\n",
      "    return once_fn(*arg, **kw)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/strategies.py\", line 199, in first_connect\n",
      "    dialect.initialize(c)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/pg8000.py\", line 215, in initialize\n",
      "    super(PGDialect_pg8000, self).initialize(connection)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py\", line 2611, in initialize\n",
      "    super(PGDialect, self).initialize(connection)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 312, in initialize\n",
      "    self.server_version_info = self._get_server_version_info(\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/base.py\", line 2856, in _get_server_version_info\n",
      "    v = connection.execute(\"select version()\").scalar()\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1003, in execute\n",
      "    return self._execute_text(object_, multiparams, params)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1172, in _execute_text\n",
      "    ret = self._execute_context(\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1316, in _execute_context\n",
      "    self._handle_dbapi_exception(\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1514, in _handle_dbapi_exception\n",
      "    util.raise_(exc_info[1], with_traceback=exc_info[2])\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/util/compat.py\", line 182, in raise_\n",
      "    raise exception\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/base.py\", line 1294, in _execute_context\n",
      "    result = context._setup_crud_result_proxy()\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 1243, in _setup_crud_result_proxy\n",
      "    result = self.get_result_proxy()\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/default.py\", line 1218, in get_result_proxy\n",
      "    return result.ResultProxy(self)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 775, in __init__\n",
      "    self._init_metadata()\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 807, in _init_metadata\n",
      "    self._metadata = ResultMetaData(self, cursor_description)\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 290, in __init__\n",
      "    raw = self._merge_cursor_description(\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 496, in _merge_cursor_description\n",
      "    return [\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 496, in <listcomp>\n",
      "    return [\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 616, in _merge_cols_by_none\n",
      "    for (\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_pip-install/packages/lib/python3.8/site-packages/sqlalchemy/engine/result.py\", line 545, in _colnames_from_description\n",
      "    colname = description_decoder(colname)\n",
      "TypeError: expected bytes, str found\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/site-packages/pygments/styles/__init__.py\", line 45, in get_style_by_name\n",
      "ModuleNotFoundError: No module named 'pygments.styles.default'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/site-packages/IPython/core/interactiveshell.py\", line 2105, in showtraceback\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1396, in structured_traceback\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1287, in structured_traceback\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1140, in structured_traceback\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1030, in format_exception_as_a_whole\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/site-packages/IPython/core/ultratb.py\", line 1081, in get_records\n",
      "  File \"/home/workspaceuser/layers/paketo-buildpacks_cpython/cpython/lib/python3.8/site-packages/pygments/styles/__init__.py\", line 47, in get_style_by_name\n",
      "pygments.util.ClassNotFound: Could not find style module 'pygments.styles.default', though it should be builtin.\n"
     ]
    }
   ],
   "source": [
    "import tasks\n",
    "tasks.load_locations()"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.16"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
